### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by mrakitin**
* Add a missing globus-sdk package

### CODE REVIEW

**Comment by mrakitin** [comment]
**Note:** with the in-place installation of `py4xs` and `globus-sdk` it tries to downgrade `ipython` to v5. It should not happen for the pre-installed packages.

I think it's good to go.

**Review by AbbyGi — APPROVED** [review]
Looks good.

**Comment by mrakitin** [comment]
Lin / @lyang11973, please note the change to the `EpicsSignalBase` timeout I was referring to before over email. Do you have it somewhere locally on a beamline workstation that was not pushed here? If so, you may want to push your changes to `master`, and I will rebase here in this PR branch.

**Comment by lyang11973** [comment]
Done
    On Tuesday, February 23, 2021, 01:24:27 PM EST, Maksim Rakitin <notifications@github.com> wrote:  
 
 


Lin / @lyang11973, please note the change to the EpicsSignalBase timeout I was referring to before over email. Do you have it somewhere locally on a beamline workstation that was not pushed here? If so, you may want to push your changes to master, and I will rebase here in this PR branch.

**Comment by mrakitin** [comment]
@lyang11973, it now fails on a missing package `lixtools` - https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=1761&view=logs&j=8d99ad36-e016-5305-6a8b-ec3199d20735&t=08a64ba8-8a08-5bdc-b64e-31b90ed23091&l=837. Where does it come from? Should we package it with conda?

**Comment by lyang11973** [comment]
Yes please. I split out some part of py4xs that is specific to the beamline.

**Comment by mrakitin** [comment]
This PR is ready for review/merge. The `lixtools` package was packaged via https://github.com/nsls-ii-forge/lixtools-feedstock/pull/1 and uploaded to the [`nsls2forge`](https://anaconda.org/nsls2forge/lixtools) conda channel. In the next cycle, it should be available in the deployed collection conda environment without any extra installation step.

**Comment by mrakitin** [comment]
@jklynch, do you mind reviewing/merging this PR? I remember you were involved in the latest deployment.

**Review by jklynch — APPROVED** [review]

**Comment by mrakitin** [comment]
Thank you, @jklynch!

**Pull request merged**
